pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
            steps {
                sh '''
                    apt-get update
                    apt-get install -y python3 python3-venv python3-pip
                '''
            }
        }

        stage('Setup Virtual Environment') {
            steps {
                sh '''
                    python33 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install pytest
                '''
            }
        }

        stage('Run Test Stage 1') {
            steps {
                sh '''
                    . venv/bin/activate
                    pytest tests/test_part1.py
                '''
            }
        }

        stage('Run Test Stage 2') {
            steps {
                sh '''
                    . venv/bin/activate
                    pytest tests/test_part2.py
                '''
            }
        }

        stage('Run Test Stage 3') {
            steps {
                sh '''
                    . venv/bin/activate
                    pytest tests/test_part3.py
                '''
            }
        }
    }
}
